baseURL: https://strathearngeeks.github.io/
theme: github.com/dwhweb/strath_geeks_theme
languageCode: en-gb
title: Strathearn Geeks
author: Strathearn Geeks
canonifyurls: true

menu:
  main:
    - name: Credits
      url: /credits
      weight: 10

# Required to stop Hugo from stripping html tags when using markdownify
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  tagline: A meetup for makers, coders, designers, 3d printers, and all tech-minded folks in Crieff and the surrounding areas.
  images:
    - twitter_card.png
