baseURL: https://strathearngeeks.github.io/
languageCode: en-gb
title: Strathearn Geeks
author: Strathearn Geeks
canonifyurls: true

theme: strath_geeks_theme
module:
  imports:
    path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5

menu:
  main:
    - name: Credits
      url: /credits
      weight: 10

# Required to stop Hugo from stripping html tags when using markdownify
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  tagline: A meetup for makers, coders, designers, and other tech-minded folk in Crieff and the surrounding areas.
  images:
    - twitter_card.png
